#   ---Plugin by niklas1623---
#
#   Copyright © 2020 niklas1623. Alle Rechte vorbehalten.
#
#   Nutze %player% für den Spielernamen
#

Settings:
    Prefix: '&8&l[&e&lDaily&b&lReward&8&l]'
    RewardCommand: 'minecraft:give %player% stone 1'


#Wenn du eine Datenbank benutzten möchtest und du MySQL hast dann kannst du dies hier einstellen.

Database:
    username: username
    password: passwort
    database: BanManager
    host: localhost
    port: '3306'
    

